info:                                                                                                             
  version: 1.0.0                                                                                                  
  description: SMF initial local configuration                                                                    
                                                                                                                  
configuration:                                                                                                    
  smfName: SMF # the name of this SMF                                                                             
  sbi: # Service-based interface information                                                                      
    scheme: http # the protocol for sbi (http or https)                                                           
    registerIPv4: 127.0.0.2 # IP used to register to NRF                                                          
    bindingIPv4: 127.0.0.2  # IP used to bind the service                                                         
    port: 8000 # Port used to bind the service                                                                    
    tls: # the local path of TLS key                                                                              
      key: free5gc/support/TLS/smf.key # SMF TLS Certificate                                                      
      pem: free5gc/support/TLS/smf.pem # SMF TLS Private key                                                      
  serviceNameList: # the SBI services provided by this SMF, refer to TS 29.502                                    
    - nsmf-pdusession # Nsmf_PDUSession service                                                                   
    - nsmf-event-exposure # Nsmf_EventExposure service                                                            
    - nsmf-oam # OAM service                                                                                      
  snssaiInfos: # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF   
    - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)                                   
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)                                                      
        sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)                              
      dnnInfos: # DNN information list                                                                            
        - dnn: internet # Data Network Name                                                                       
          dns: # the IP address of DNS                                                                            
            ipv4: 8.8.8.8                                                                                         
            ipv6: 2001:4860:4860::8888                                                                            
          ueSubnet: 60.60.0.0/16 # should be CIDR type                                                            
    - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)                                   
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)                                                      
        sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)                              
      dnnInfos: # DNN information list                                                                            
        - dnn: internet # Data Network Name                                                                       
          dns: # the IP address of DNS                                                                            
            ipv4: 8.8.8.8                                                                                         
            ipv6: 2001:4860:4860::8888                                                                            
          ueSubnet: 60.61.0.0/16 # should be CIDR type                                                            
  pfcp: # the IP address of N4 interface on this SMF (PFCP)                                                       
    addr: 10.10.1.2                                                                                               
  userplane_information: # list of userplane information                                                          
    up_nodes:                                                                                                     
      gNB1:                                                                                                       
        type: AN                                                                                                  
        an_ip: 10.10.1.1                                                                                          
      BranchingUPF:                                                                                               
        type: UPF                                                                                                 
        node_id: 10.10.1.3                                                                                        
        sNssaiUpfInfos: # S-NSSAI information list for this UPF                                                   
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)                             
              sst: 1 # Slice/Service Type (uinteger, range: 0~255)                                                
              sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)                        
            dnnUpfInfoList: # DNN information list for this S-NSSAI                                               
              - dnn: internet                                                                                     
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)                             
              sst: 1 # Slice/Service Type (uinteger, range: 0~255)                                                
              sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)                        
            dnnUpfInfoList: # DNN information list for this S-NSSAI                                               
              - dnn: internet                                                                                     
        interfaces: # Interface list for this UPF                                                                 
          - interfaceType: N3 # the type of the interface (N3 or N9)                                              
            endpoints: # the IP address of this N3/N9 interface on this UPF                                       
              - 10.10.1.3                                                                                         
      AnchorUPF1:                                                                                                 
        type: UPF                                                                                                 
        node_id: 10.10.1.4                                                                                        
      AnchorUPF2:                                                                                                 
        type: UPF                                                                                                 
        node_id: 10.10.1.5                                                                                        
    links:                                                                                                        
      - A: gNB1                                                                                                   
        B: BranchingUPF                                                                                           
      - A: BranchingUPF                                                                                           
        B: AnchorUPF1                                                                                             
      - A: BranchingUPF                                                                                           
        B: AnchorUPF2                                                                                             
                                                                                                                  
  nrfUri: http://127.0.0.10:8000 # a valid URI of NRF                                                             
  ulcl: true                                                                                                      
                                                                                                                  
# the kind of log output                                                                                          
  # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic                      
  # ReportCaller: enable the caller report or not, value: true or false                                           
logger:                                                                                                           
  SMF:                                                                                                            
    debugLevel: info                                                                                              
    ReportCaller: false                                                                                           
  NAS:                                                                                                            
    debugLevel: info                                                                                              
    ReportCaller: false                                                                                           
  NGAP:                                                                                                           
    debugLevel: info                                                                                              
    ReportCaller: false                                                                                           
  Aper:                                                                                                           
    debugLevel: info                                                                                              
    ReportCaller: false                                                                                           
  PathUtil:                                                                                                       
    debugLevel: info                                                                                              
    ReportCaller: false                                                                                           
  OpenApi:                                                                                                        
    debugLevel: info                                                                                              
    ReportCaller: false                                                                                           
  PFCP:                                                                                                           
    debugLevel: info                                                                                              
    ReportCaller: false                                                                                           
